// src/js/constants/index.js

export const REST_API_ERROR = 'REST_API_ERROR'

export const REST_SEARCH_SUGGESTIONS_CLEAR = 'REST_SEARCH_SUGGESTIONS_CLEAR'
export const REST_SEARCH_SUGGESTIONS_GET = 'REST_SEARCH_SUGGESTIONS_GET'
export const REST_SEARCH_SUGGESTIONS_GOT = 'REST_SEARCH_SUGGESTIONS_GOT'

export const REST_SEARCH_RESULTS_CLEAR = 'REST_SEARCH_RESULTS_CLEAR'
export const REST_SEARCH_RESULTS_GET = 'REST_SEARCH_RESULTS_GET'
export const REST_SEARCH_RESULTS_GOT = 'REST_SEARCH_RESULTS_GOT'
export const REST_SEARCH_RESULTS_LOADED = 'REST_SEARCH_RESULTS_LOADED'

